package reversedb.modelo2;
// Generated Jun 10, 2015 7:53:33 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CvcClaseVehiRepuve generated by hbm2java
 */
@Entity
@Table(name="CVC_CLASE_VEHI_REPUVE"
    ,schema="SIR7_ING"
)
public class CvcClaseVehiRepuve  implements java.io.Serializable {


     private String idClaseVehi;
     private String descClaseVehi;
     private boolean idClaseRpv;
     private String descClaseRpv;
     private String idStatus;
     private Date fechaInicio;
     private Date fechaMov;
     private Set<CvcTipoVehiRepuve> cvcTipoVehiRepuves = new HashSet<CvcTipoVehiRepuve>(0);
     private Set<TepVehiculo> tepVehiculos = new HashSet<TepVehiculo>(0);

    public CvcClaseVehiRepuve() {
    }

	
    public CvcClaseVehiRepuve(String idClaseVehi, String descClaseVehi, boolean idClaseRpv, String descClaseRpv, String idStatus, Date fechaInicio, Date fechaMov) {
        this.idClaseVehi = idClaseVehi;
        this.descClaseVehi = descClaseVehi;
        this.idClaseRpv = idClaseRpv;
        this.descClaseRpv = descClaseRpv;
        this.idStatus = idStatus;
        this.fechaInicio = fechaInicio;
        this.fechaMov = fechaMov;
    }
    public CvcClaseVehiRepuve(String idClaseVehi, String descClaseVehi, boolean idClaseRpv, String descClaseRpv, String idStatus, Date fechaInicio, Date fechaMov, Set<CvcTipoVehiRepuve> cvcTipoVehiRepuves, Set<TepVehiculo> tepVehiculos) {
       this.idClaseVehi = idClaseVehi;
       this.descClaseVehi = descClaseVehi;
       this.idClaseRpv = idClaseRpv;
       this.descClaseRpv = descClaseRpv;
       this.idStatus = idStatus;
       this.fechaInicio = fechaInicio;
       this.fechaMov = fechaMov;
       this.cvcTipoVehiRepuves = cvcTipoVehiRepuves;
       this.tepVehiculos = tepVehiculos;
    }
   
     @Id 

    
    @Column(name="ID_CLASE_VEHI", unique=true, nullable=false, length=2)
    public String getIdClaseVehi() {
        return this.idClaseVehi;
    }
    
    public void setIdClaseVehi(String idClaseVehi) {
        this.idClaseVehi = idClaseVehi;
    }

    
    @Column(name="DESC_CLASE_VEHI", nullable=false, length=50)
    public String getDescClaseVehi() {
        return this.descClaseVehi;
    }
    
    public void setDescClaseVehi(String descClaseVehi) {
        this.descClaseVehi = descClaseVehi;
    }

    
    @Column(name="ID_CLASE_RPV", nullable=false, precision=1, scale=0)
    public boolean isIdClaseRpv() {
        return this.idClaseRpv;
    }
    
    public void setIdClaseRpv(boolean idClaseRpv) {
        this.idClaseRpv = idClaseRpv;
    }

    
    @Column(name="DESC_CLASE_RPV", nullable=false, length=30)
    public String getDescClaseRpv() {
        return this.descClaseRpv;
    }
    
    public void setDescClaseRpv(String descClaseRpv) {
        this.descClaseRpv = descClaseRpv;
    }

    
    @Column(name="ID_STATUS", nullable=false, length=2)
    public String getIdStatus() {
        return this.idStatus;
    }
    
    public void setIdStatus(String idStatus) {
        this.idStatus = idStatus;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_INICIO", nullable=false, length=7)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_MOV", nullable=false, length=7)
    public Date getFechaMov() {
        return this.fechaMov;
    }
    
    public void setFechaMov(Date fechaMov) {
        this.fechaMov = fechaMov;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cvcClaseVehiRepuve")
    public Set<CvcTipoVehiRepuve> getCvcTipoVehiRepuves() {
        return this.cvcTipoVehiRepuves;
    }
    
    public void setCvcTipoVehiRepuves(Set<CvcTipoVehiRepuve> cvcTipoVehiRepuves) {
        this.cvcTipoVehiRepuves = cvcTipoVehiRepuves;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cvcClaseVehiRepuve")
    public Set<TepVehiculo> getTepVehiculos() {
        return this.tepVehiculos;
    }
    
    public void setTepVehiculos(Set<TepVehiculo> tepVehiculos) {
        this.tepVehiculos = tepVehiculos;
    }




}


