package reversedb.modelo2;
// Generated Jun 10, 2015 7:53:33 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * CvcColorvehi generated by hbm2java
 */
@Entity
@Table(name="CVC_COLORVEHI"
)
public class CvcColorvehi  implements java.io.Serializable {


     private short clavecolor;
     private String descripcion;
     private String idStatus;
     private Date fechaMov;
     private Set<TepVehiculo> tepVehiculos = new HashSet<TepVehiculo>(0);

    public CvcColorvehi() {
    }

	
    public CvcColorvehi(short clavecolor, String descripcion, String idStatus, Date fechaMov) {
        this.clavecolor = clavecolor;
        this.descripcion = descripcion;
        this.idStatus = idStatus;
        this.fechaMov = fechaMov;
    }
    public CvcColorvehi(short clavecolor, String descripcion, String idStatus, Date fechaMov, Set<TepVehiculo> tepVehiculos) {
       this.clavecolor = clavecolor;
       this.descripcion = descripcion;
       this.idStatus = idStatus;
       this.fechaMov = fechaMov;
       this.tepVehiculos = tepVehiculos;
    }
   
     @Id 

    
    @Column(name="CLAVECOLOR", unique=true, nullable=false, precision=4, scale=0)
    public short getClavecolor() {
        return this.clavecolor;
    }
    
    public void setClavecolor(short clavecolor) {
        this.clavecolor = clavecolor;
    }

    
    @Column(name="DESCRIPCION", nullable=false, length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="ID_STATUS", nullable=false, length=2)
    public String getIdStatus() {
        return this.idStatus;
    }
    
    public void setIdStatus(String idStatus) {
        this.idStatus = idStatus;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_MOV", nullable=false, length=7)
    public Date getFechaMov() {
        return this.fechaMov;
    }
    
    public void setFechaMov(Date fechaMov) {
        this.fechaMov = fechaMov;
    }

//@OneToMany(fetch=FetchType.LAZY, mappedBy="cvcColorvehi")
    @Transient
    public Set<TepVehiculo> getTepVehiculos() {
        return this.tepVehiculos;
    }
    
    public void setTepVehiculos(Set<TepVehiculo> tepVehiculos) {
        this.tepVehiculos = tepVehiculos;
    }




}


