package reversedb.modelo2;
// Generated Jun 10, 2015 7:53:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CvcMotivobajas generated by hbm2java
 */
@Entity
@Table(name="CVC_MOTIVOBAJAS"
    ,schema="SIR7_ING"
)
public class CvcMotivobajas  implements java.io.Serializable {


     private short idMotivobaja;
     private String descripcion;
     private boolean eleccion;
     private String idStatus;
     private Set<TetControlTramite> tetControlTramites = new HashSet<TetControlTramite>(0);

    public CvcMotivobajas() {
    }

	
    public CvcMotivobajas(short idMotivobaja, String descripcion, boolean eleccion, String idStatus) {
        this.idMotivobaja = idMotivobaja;
        this.descripcion = descripcion;
        this.eleccion = eleccion;
        this.idStatus = idStatus;
    }
    public CvcMotivobajas(short idMotivobaja, String descripcion, boolean eleccion, String idStatus, Set<TetControlTramite> tetControlTramites) {
       this.idMotivobaja = idMotivobaja;
       this.descripcion = descripcion;
       this.eleccion = eleccion;
       this.idStatus = idStatus;
       this.tetControlTramites = tetControlTramites;
    }
   
     @Id 

    
    @Column(name="ID_MOTIVOBAJA", unique=true, nullable=false, precision=3, scale=0)
    public short getIdMotivobaja() {
        return this.idMotivobaja;
    }
    
    public void setIdMotivobaja(short idMotivobaja) {
        this.idMotivobaja = idMotivobaja;
    }

    
    @Column(name="DESCRIPCION", nullable=false, length=30)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="ELECCION", nullable=false, precision=1, scale=0)
    public boolean isEleccion() {
        return this.eleccion;
    }
    
    public void setEleccion(boolean eleccion) {
        this.eleccion = eleccion;
    }

    
    @Column(name="ID_STATUS", nullable=false, length=2)
    public String getIdStatus() {
        return this.idStatus;
    }
    
    public void setIdStatus(String idStatus) {
        this.idStatus = idStatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cvcMotivobajas")
    public Set<TetControlTramite> getTetControlTramites() {
        return this.tetControlTramites;
    }
    
    public void setTetControlTramites(Set<TetControlTramite> tetControlTramites) {
        this.tetControlTramites = tetControlTramites;
    }




}


