package reversedb.modelo2;
// Generated Jun 10, 2015 7:53:33 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CvcTransmisionRepuve generated by hbm2java
 */
@Entity
@Table(name="CVC_TRANSMISION_REPUVE"
    ,schema="SIR7_ING"
)
public class CvcTransmisionRepuve  implements java.io.Serializable {


     private String idTransmision;
     private String descTransmision;
     private String idStatus;
     private Date fechaInicio;
     private Date fechaMov;
     private Set<TepVehiculo> tepVehiculos = new HashSet<TepVehiculo>(0);

    public CvcTransmisionRepuve() {
    }

	
    public CvcTransmisionRepuve(String idTransmision, String descTransmision, String idStatus, Date fechaInicio, Date fechaMov) {
        this.idTransmision = idTransmision;
        this.descTransmision = descTransmision;
        this.idStatus = idStatus;
        this.fechaInicio = fechaInicio;
        this.fechaMov = fechaMov;
    }
    public CvcTransmisionRepuve(String idTransmision, String descTransmision, String idStatus, Date fechaInicio, Date fechaMov, Set<TepVehiculo> tepVehiculos) {
       this.idTransmision = idTransmision;
       this.descTransmision = descTransmision;
       this.idStatus = idStatus;
       this.fechaInicio = fechaInicio;
       this.fechaMov = fechaMov;
       this.tepVehiculos = tepVehiculos;
    }
   
     @Id 

    
    @Column(name="ID_TRANSMISION", unique=true, nullable=false, length=2)
    public String getIdTransmision() {
        return this.idTransmision;
    }
    
    public void setIdTransmision(String idTransmision) {
        this.idTransmision = idTransmision;
    }

    
    @Column(name="DESC_TRANSMISION", nullable=false, length=20)
    public String getDescTransmision() {
        return this.descTransmision;
    }
    
    public void setDescTransmision(String descTransmision) {
        this.descTransmision = descTransmision;
    }

    
    @Column(name="ID_STATUS", nullable=false, length=2)
    public String getIdStatus() {
        return this.idStatus;
    }
    
    public void setIdStatus(String idStatus) {
        this.idStatus = idStatus;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_INICIO", nullable=false, length=7)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_MOV", nullable=false, length=7)
    public Date getFechaMov() {
        return this.fechaMov;
    }
    
    public void setFechaMov(Date fechaMov) {
        this.fechaMov = fechaMov;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cvcTransmisionRepuve")
    public Set<TepVehiculo> getTepVehiculos() {
        return this.tepVehiculos;
    }
    
    public void setTepVehiculos(Set<TepVehiculo> tepVehiculos) {
        this.tepVehiculos = tepVehiculos;
    }




}


