package reversedb.modelo2;
// Generated Jun 10, 2015 7:53:33 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CvcTipoplacaweb generated by hbm2java
 */
@Entity
@Table(name="CVC_TIPOPLACAWEB"
    ,schema="SIR7_ING"
)
public class CvcTipoplacaweb  implements java.io.Serializable {


     private BigDecimal tipoPlaca;
     private String descripcion;
     private Set<TetControlTramite> tetControlTramites = new HashSet<TetControlTramite>(0);

    public CvcTipoplacaweb() {
    }

	
    public CvcTipoplacaweb(BigDecimal tipoPlaca, String descripcion) {
        this.tipoPlaca = tipoPlaca;
        this.descripcion = descripcion;
    }
    public CvcTipoplacaweb(BigDecimal tipoPlaca, String descripcion, Set<TetControlTramite> tetControlTramites) {
       this.tipoPlaca = tipoPlaca;
       this.descripcion = descripcion;
       this.tetControlTramites = tetControlTramites;
    }
   
     @Id 

    
    @Column(name="TIPO_PLACA", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getTipoPlaca() {
        return this.tipoPlaca;
    }
    
    public void setTipoPlaca(BigDecimal tipoPlaca) {
        this.tipoPlaca = tipoPlaca;
    }

    
    @Column(name="DESCRIPCION", nullable=false, length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cvcTipoplacaweb")
    public Set<TetControlTramite> getTetControlTramites() {
        return this.tetControlTramites;
    }
    
    public void setTetControlTramites(Set<TetControlTramite> tetControlTramites) {
        this.tetControlTramites = tetControlTramites;
    }




}


