package reversedb.modelo2;
// Generated Jun 10, 2015 7:53:33 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CvcUsoVehiRepuve generated by hbm2java
 */
@Entity
@Table(name="CVC_USO_VEHI_REPUVE"
    ,schema="SIR7_ING"
)
public class CvcUsoVehiRepuve  implements java.io.Serializable {


     private byte idUsoVehi;
     private String descUsoVehi;
     private String idStatus;
     private Date fechaInicio;
     private Date fechaMov;
     private Boolean exento;
     private Set<TepVehiculo> tepVehiculos = new HashSet<TepVehiculo>(0);

    public CvcUsoVehiRepuve() {
    }

	
    public CvcUsoVehiRepuve(byte idUsoVehi, String descUsoVehi, String idStatus, Date fechaInicio, Date fechaMov) {
        this.idUsoVehi = idUsoVehi;
        this.descUsoVehi = descUsoVehi;
        this.idStatus = idStatus;
        this.fechaInicio = fechaInicio;
        this.fechaMov = fechaMov;
    }
    public CvcUsoVehiRepuve(byte idUsoVehi, String descUsoVehi, String idStatus, Date fechaInicio, Date fechaMov, Boolean exento, Set<TepVehiculo> tepVehiculos) {
       this.idUsoVehi = idUsoVehi;
       this.descUsoVehi = descUsoVehi;
       this.idStatus = idStatus;
       this.fechaInicio = fechaInicio;
       this.fechaMov = fechaMov;
       this.exento = exento;
       this.tepVehiculos = tepVehiculos;
    }
   
     @Id 

    
    @Column(name="ID_USO_VEHI", unique=true, nullable=false, precision=2, scale=0)
    public byte getIdUsoVehi() {
        return this.idUsoVehi;
    }
    
    public void setIdUsoVehi(byte idUsoVehi) {
        this.idUsoVehi = idUsoVehi;
    }

    
    @Column(name="DESC_USO_VEHI", nullable=false, length=70)
    public String getDescUsoVehi() {
        return this.descUsoVehi;
    }
    
    public void setDescUsoVehi(String descUsoVehi) {
        this.descUsoVehi = descUsoVehi;
    }

    
    @Column(name="ID_STATUS", nullable=false, length=2)
    public String getIdStatus() {
        return this.idStatus;
    }
    
    public void setIdStatus(String idStatus) {
        this.idStatus = idStatus;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_INICIO", nullable=false, length=7)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_MOV", nullable=false, length=7)
    public Date getFechaMov() {
        return this.fechaMov;
    }
    
    public void setFechaMov(Date fechaMov) {
        this.fechaMov = fechaMov;
    }

    
    @Column(name="EXENTO", precision=1, scale=0)
    public Boolean getExento() {
        return this.exento;
    }
    
    public void setExento(Boolean exento) {
        this.exento = exento;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cvcUsoVehiRepuve")
    public Set<TepVehiculo> getTepVehiculos() {
        return this.tepVehiculos;
    }
    
    public void setTepVehiculos(Set<TepVehiculo> tepVehiculos) {
        this.tepVehiculos = tepVehiculos;
    }




}


