package reversedb.modelo2;
// Generated Jun 10, 2015 7:53:33 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IcPeriodos generated by hbm2java
 */
@Entity
@Table(name="IC_PERIODOS"
    ,schema="SIR7_ING"
)
public class IcPeriodos  implements java.io.Serializable {


     private BigDecimal claveperiodo;
     private String descripcion;
     private Date fechainicio;
     private Date fechafin;
     private BigDecimal claveestado;
     private Set<ItServicios> itServicioses = new HashSet<ItServicios>(0);

    public IcPeriodos() {
    }

	
    public IcPeriodos(BigDecimal claveperiodo) {
        this.claveperiodo = claveperiodo;
    }
    public IcPeriodos(BigDecimal claveperiodo, String descripcion, Date fechainicio, Date fechafin, BigDecimal claveestado, Set<ItServicios> itServicioses) {
       this.claveperiodo = claveperiodo;
       this.descripcion = descripcion;
       this.fechainicio = fechainicio;
       this.fechafin = fechafin;
       this.claveestado = claveestado;
       this.itServicioses = itServicioses;
    }
   
     @Id 

    
    @Column(name="CLAVEPERIODO", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getClaveperiodo() {
        return this.claveperiodo;
    }
    
    public void setClaveperiodo(BigDecimal claveperiodo) {
        this.claveperiodo = claveperiodo;
    }

    
    @Column(name="DESCRIPCION", length=30)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHAINICIO", length=7)
    public Date getFechainicio() {
        return this.fechainicio;
    }
    
    public void setFechainicio(Date fechainicio) {
        this.fechainicio = fechainicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHAFIN", length=7)
    public Date getFechafin() {
        return this.fechafin;
    }
    
    public void setFechafin(Date fechafin) {
        this.fechafin = fechafin;
    }

    
    @Column(name="CLAVEESTADO", precision=22, scale=0)
    public BigDecimal getClaveestado() {
        return this.claveestado;
    }
    
    public void setClaveestado(BigDecimal claveestado) {
        this.claveestado = claveestado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="icPeriodos")
    public Set<ItServicios> getItServicioses() {
        return this.itServicioses;
    }
    
    public void setItServicioses(Set<ItServicios> itServicioses) {
        this.itServicioses = itServicioses;
    }




}


