package reversedb.modelo2;
// Generated Jun 10, 2015 7:53:33 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ItServiciosId generated by hbm2java
 */
@Embeddable
public class ItServiciosId  implements java.io.Serializable {


     private BigDecimal claveoperacionserv;
     private BigDecimal claveperiodo;

    public ItServiciosId() {
    }

    public ItServiciosId(BigDecimal claveoperacionserv, BigDecimal claveperiodo) {
       this.claveoperacionserv = claveoperacionserv;
       this.claveperiodo = claveperiodo;
    }
   


    @Column(name="CLAVEOPERACIONSERV", nullable=false, precision=22, scale=0)
    public BigDecimal getClaveoperacionserv() {
        return this.claveoperacionserv;
    }
    
    public void setClaveoperacionserv(BigDecimal claveoperacionserv) {
        this.claveoperacionserv = claveoperacionserv;
    }


    @Column(name="CLAVEPERIODO", nullable=false, precision=22, scale=0)
    public BigDecimal getClaveperiodo() {
        return this.claveperiodo;
    }
    
    public void setClaveperiodo(BigDecimal claveperiodo) {
        this.claveperiodo = claveperiodo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ItServiciosId) ) return false;
		 ItServiciosId castOther = ( ItServiciosId ) other; 
         
		 return ( (this.getClaveoperacionserv()==castOther.getClaveoperacionserv()) || ( this.getClaveoperacionserv()!=null && castOther.getClaveoperacionserv()!=null && this.getClaveoperacionserv().equals(castOther.getClaveoperacionserv()) ) )
 && ( (this.getClaveperiodo()==castOther.getClaveperiodo()) || ( this.getClaveperiodo()!=null && castOther.getClaveperiodo()!=null && this.getClaveperiodo().equals(castOther.getClaveperiodo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getClaveoperacionserv() == null ? 0 : this.getClaveoperacionserv().hashCode() );
         result = 37 * result + ( getClaveperiodo() == null ? 0 : this.getClaveperiodo().hashCode() );
         return result;
   }   


}


