package reversedb.modelo2;
// Generated Jun 10, 2015 7:53:33 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ItServicios generated by hbm2java
 */
@Entity
@Table(name="IT_SERVICIOS"
    ,schema="SIR7_ING"
)
public class ItServicios  implements java.io.Serializable {


     private ItServiciosId id;
     private IcPeriodos icPeriodos;
     private BigDecimal total;
     private Date fecha;
     private String referencia;
     private BigDecimal clavetipooperserv;
     private Date fechalimite;
     private BigDecimal claveestado;
     private BigDecimal importetotal;
     private BigDecimal importesubsidio;
     private Set<TetControlTramite> tetControlTramites = new HashSet<TetControlTramite>(0);

    public ItServicios() {
    }

	
    public ItServicios(ItServiciosId id, IcPeriodos icPeriodos) {
        this.id = id;
        this.icPeriodos = icPeriodos;
    }
    public ItServicios(ItServiciosId id, IcPeriodos icPeriodos, BigDecimal total, Date fecha, String referencia, BigDecimal clavetipooperserv, Date fechalimite, BigDecimal claveestado, BigDecimal importetotal, BigDecimal importesubsidio, Set<TetControlTramite> tetControlTramites) {
       this.id = id;
       this.icPeriodos = icPeriodos;
       this.total = total;
       this.fecha = fecha;
       this.referencia = referencia;
       this.clavetipooperserv = clavetipooperserv;
       this.fechalimite = fechalimite;
       this.claveestado = claveestado;
       this.importetotal = importetotal;
       this.importesubsidio = importesubsidio;
       this.tetControlTramites = tetControlTramites;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="claveoperacionserv", column=@Column(name="CLAVEOPERACIONSERV", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="claveperiodo", column=@Column(name="CLAVEPERIODO", nullable=false, precision=22, scale=0) ) } )
    public ItServiciosId getId() {
        return this.id;
    }
    
    public void setId(ItServiciosId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLAVEPERIODO", nullable=false, insertable=false, updatable=false)
    public IcPeriodos getIcPeriodos() {
        return this.icPeriodos;
    }
    
    public void setIcPeriodos(IcPeriodos icPeriodos) {
        this.icPeriodos = icPeriodos;
    }

    
    @Column(name="TOTAL", precision=22, scale=0)
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA", length=7)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="REFERENCIA", length=27)
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }

    
    @Column(name="CLAVETIPOOPERSERV", precision=22, scale=0)
    public BigDecimal getClavetipooperserv() {
        return this.clavetipooperserv;
    }
    
    public void setClavetipooperserv(BigDecimal clavetipooperserv) {
        this.clavetipooperserv = clavetipooperserv;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHALIMITE", length=7)
    public Date getFechalimite() {
        return this.fechalimite;
    }
    
    public void setFechalimite(Date fechalimite) {
        this.fechalimite = fechalimite;
    }

    
    @Column(name="CLAVEESTADO", precision=22, scale=0)
    public BigDecimal getClaveestado() {
        return this.claveestado;
    }
    
    public void setClaveestado(BigDecimal claveestado) {
        this.claveestado = claveestado;
    }

    
    @Column(name="IMPORTETOTAL", precision=14)
    public BigDecimal getImportetotal() {
        return this.importetotal;
    }
    
    public void setImportetotal(BigDecimal importetotal) {
        this.importetotal = importetotal;
    }

    
    @Column(name="IMPORTESUBSIDIO", precision=14)
    public BigDecimal getImportesubsidio() {
        return this.importesubsidio;
    }
    
    public void setImportesubsidio(BigDecimal importesubsidio) {
        this.importesubsidio = importesubsidio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="itServicios")
    public Set<TetControlTramite> getTetControlTramites() {
        return this.tetControlTramites;
    }
    
    public void setTetControlTramites(Set<TetControlTramite> tetControlTramites) {
        this.tetControlTramites = tetControlTramites;
    }




}


