package reversedb.modelo2;
// Generated Jun 10, 2015 7:53:33 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RgcAsentamiento generated by hbm2java
 */
@Entity
@Table(name="RGC_ASENTAMIENTO"
    ,schema="SIR7_ING"
)
public class RgcAsentamiento  implements java.io.Serializable {


     private RgcAsentamientoId id;
     private RgcTipoasenta rgcTipoasenta;
     private RgcCp rgcCp;
     private String descripcion;
     private Date fechainicio;
     private Date fechafin;
     private Set<SgpOficina> sgpOficinas = new HashSet<SgpOficina>(0);

    public RgcAsentamiento() {
    }

	
    public RgcAsentamiento(RgcAsentamientoId id, RgcCp rgcCp) {
        this.id = id;
        this.rgcCp = rgcCp;
    }
    public RgcAsentamiento(RgcAsentamientoId id, RgcTipoasenta rgcTipoasenta, RgcCp rgcCp, String descripcion, Date fechainicio, Date fechafin, Set<SgpOficina> sgpOficinas) {
       this.id = id;
       this.rgcTipoasenta = rgcTipoasenta;
       this.rgcCp = rgcCp;
       this.descripcion = descripcion;
       this.fechainicio = fechainicio;
       this.fechafin = fechafin;
       this.sgpOficinas = sgpOficinas;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="claveasentamiento", column=@Column(name="CLAVEASENTAMIENTO", nullable=false, precision=4, scale=0) ), 
        @AttributeOverride(name="clavecp", column=@Column(name="CLAVECP", nullable=false, length=5) ), 
        @AttributeOverride(name="claveentidad", column=@Column(name="CLAVEENTIDAD", nullable=false, precision=2, scale=0) ), 
        @AttributeOverride(name="clavemunicipio", column=@Column(name="CLAVEMUNICIPIO", nullable=false, precision=4, scale=0) ) } )
    public RgcAsentamientoId getId() {
        return this.id;
    }
    
    public void setId(RgcAsentamientoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLAVETIPOASENTA")
    public RgcTipoasenta getRgcTipoasenta() {
        return this.rgcTipoasenta;
    }
    
    public void setRgcTipoasenta(RgcTipoasenta rgcTipoasenta) {
        this.rgcTipoasenta = rgcTipoasenta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="CLAVECP", referencedColumnName="CLAVECP", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="CLAVEENTIDAD", referencedColumnName="CLAVEENTIDAD", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="CLAVEMUNICIPIO", referencedColumnName="CLAVEMUNICIPIO", nullable=false, insertable=false, updatable=false) } )
    public RgcCp getRgcCp() {
        return this.rgcCp;
    }
    
    public void setRgcCp(RgcCp rgcCp) {
        this.rgcCp = rgcCp;
    }

    
    @Column(name="DESCRIPCION", length=60)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHAINICIO", length=7)
    public Date getFechainicio() {
        return this.fechainicio;
    }
    
    public void setFechainicio(Date fechainicio) {
        this.fechainicio = fechainicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHAFIN", length=7)
    public Date getFechafin() {
        return this.fechafin;
    }
    
    public void setFechafin(Date fechafin) {
        this.fechafin = fechafin;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rgcAsentamiento")
    public Set<SgpOficina> getSgpOficinas() {
        return this.sgpOficinas;
    }
    
    public void setSgpOficinas(Set<SgpOficina> sgpOficinas) {
        this.sgpOficinas = sgpOficinas;
    }




}


