package reversedb.modelo2;
// Generated Jun 10, 2015 7:53:33 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RgcEntidad generated by hbm2java
 */
@Entity
@Table(name="RGC_ENTIDAD"
    ,schema="SIR7_ING"
)
public class RgcEntidad  implements java.io.Serializable {


     private byte claveentidad;
     private RgcPais rgcPais;
     private String descripcion;
     private String abreviatura;
     private Date fechainicio;
     private Date fechafin;
     private Set<RgcMunicipio> rgcMunicipios = new HashSet<RgcMunicipio>(0);

    public RgcEntidad() {
    }

	
    public RgcEntidad(byte claveentidad) {
        this.claveentidad = claveentidad;
    }
    public RgcEntidad(byte claveentidad, RgcPais rgcPais, String descripcion, String abreviatura, Date fechainicio, Date fechafin, Set<RgcMunicipio> rgcMunicipios) {
       this.claveentidad = claveentidad;
       this.rgcPais = rgcPais;
       this.descripcion = descripcion;
       this.abreviatura = abreviatura;
       this.fechainicio = fechainicio;
       this.fechafin = fechafin;
       this.rgcMunicipios = rgcMunicipios;
    }
   
     @Id 

    
    @Column(name="CLAVEENTIDAD", unique=true, nullable=false, precision=2, scale=0)
    public byte getClaveentidad() {
        return this.claveentidad;
    }
    
    public void setClaveentidad(byte claveentidad) {
        this.claveentidad = claveentidad;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLAVEPAIS")
    public RgcPais getRgcPais() {
        return this.rgcPais;
    }
    
    public void setRgcPais(RgcPais rgcPais) {
        this.rgcPais = rgcPais;
    }

    
    @Column(name="DESCRIPCION", length=30)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="ABREVIATURA", length=20)
    public String getAbreviatura() {
        return this.abreviatura;
    }
    
    public void setAbreviatura(String abreviatura) {
        this.abreviatura = abreviatura;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHAINICIO", length=7)
    public Date getFechainicio() {
        return this.fechainicio;
    }
    
    public void setFechainicio(Date fechainicio) {
        this.fechainicio = fechainicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHAFIN", length=7)
    public Date getFechafin() {
        return this.fechafin;
    }
    
    public void setFechafin(Date fechafin) {
        this.fechafin = fechafin;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rgcEntidad")
    public Set<RgcMunicipio> getRgcMunicipios() {
        return this.rgcMunicipios;
    }
    
    public void setRgcMunicipios(Set<RgcMunicipio> rgcMunicipios) {
        this.rgcMunicipios = rgcMunicipios;
    }




}


