package reversedb.modelo2;
// Generated Jun 10, 2015 7:53:33 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RgcMunicipio generated by hbm2java
 */
@Entity
@Table(name="RGC_MUNICIPIO"
    ,schema="SIR7_ING"
)
public class RgcMunicipio  implements java.io.Serializable {


     private RgcMunicipioId id;
     private RgcEntidad rgcEntidad;
     private String descripcion;
     private Date fechainicio;
     private Date fechafin;
     private String clavefiscal;
     private BigDecimal latitud;
     private BigDecimal longitud;
     private Set<RgcCp> rgcCps = new HashSet<RgcCp>(0);

    public RgcMunicipio() {
    }

	
    public RgcMunicipio(RgcMunicipioId id, RgcEntidad rgcEntidad) {
        this.id = id;
        this.rgcEntidad = rgcEntidad;
    }
    public RgcMunicipio(RgcMunicipioId id, RgcEntidad rgcEntidad, String descripcion, Date fechainicio, Date fechafin, String clavefiscal, BigDecimal latitud, BigDecimal longitud, Set<RgcCp> rgcCps) {
       this.id = id;
       this.rgcEntidad = rgcEntidad;
       this.descripcion = descripcion;
       this.fechainicio = fechainicio;
       this.fechafin = fechafin;
       this.clavefiscal = clavefiscal;
       this.latitud = latitud;
       this.longitud = longitud;
       this.rgcCps = rgcCps;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="claveentidad", column=@Column(name="CLAVEENTIDAD", nullable=false, precision=2, scale=0) ), 
        @AttributeOverride(name="clavemunicipio", column=@Column(name="CLAVEMUNICIPIO", nullable=false, precision=4, scale=0) ) } )
    public RgcMunicipioId getId() {
        return this.id;
    }
    
    public void setId(RgcMunicipioId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLAVEENTIDAD", nullable=false, insertable=false, updatable=false)
    public RgcEntidad getRgcEntidad() {
        return this.rgcEntidad;
    }
    
    public void setRgcEntidad(RgcEntidad rgcEntidad) {
        this.rgcEntidad = rgcEntidad;
    }

    
    @Column(name="DESCRIPCION", length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHAINICIO", length=7)
    public Date getFechainicio() {
        return this.fechainicio;
    }
    
    public void setFechainicio(Date fechainicio) {
        this.fechainicio = fechainicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHAFIN", length=7)
    public Date getFechafin() {
        return this.fechafin;
    }
    
    public void setFechafin(Date fechafin) {
        this.fechafin = fechafin;
    }

    
    @Column(name="CLAVEFISCAL", length=4)
    public String getClavefiscal() {
        return this.clavefiscal;
    }
    
    public void setClavefiscal(String clavefiscal) {
        this.clavefiscal = clavefiscal;
    }

    
    @Column(name="LATITUD", precision=10, scale=6)
    public BigDecimal getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(BigDecimal latitud) {
        this.latitud = latitud;
    }

    
    @Column(name="LONGITUD", precision=10, scale=6)
    public BigDecimal getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(BigDecimal longitud) {
        this.longitud = longitud;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rgcMunicipio")
    public Set<RgcCp> getRgcCps() {
        return this.rgcCps;
    }
    
    public void setRgcCps(Set<RgcCp> rgcCps) {
        this.rgcCps = rgcCps;
    }




}


