package reversedb.modelo2;
// Generated Jun 10, 2015 7:53:33 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RgcSitdom generated by hbm2java
 */
@Entity
@Table(name="RGC_SITDOM"
    ,schema="SIR7_ING"
)
public class RgcSitdom  implements java.io.Serializable {


     private byte clavesituacion;
     private String descripcion;
     private Date fechainicio;
     private Date fechafin;
     private Set<TepDomicilio> tepDomicilios = new HashSet<TepDomicilio>(0);

    public RgcSitdom() {
    }

	
    public RgcSitdom(byte clavesituacion) {
        this.clavesituacion = clavesituacion;
    }
    public RgcSitdom(byte clavesituacion, String descripcion, Date fechainicio, Date fechafin, Set<TepDomicilio> tepDomicilios) {
       this.clavesituacion = clavesituacion;
       this.descripcion = descripcion;
       this.fechainicio = fechainicio;
       this.fechafin = fechafin;
       this.tepDomicilios = tepDomicilios;
    }
   
     @Id 

    
    @Column(name="CLAVESITUACION", unique=true, nullable=false, precision=2, scale=0)
    public byte getClavesituacion() {
        return this.clavesituacion;
    }
    
    public void setClavesituacion(byte clavesituacion) {
        this.clavesituacion = clavesituacion;
    }

    
    @Column(name="DESCRIPCION", length=30)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHAINICIO", length=7)
    public Date getFechainicio() {
        return this.fechainicio;
    }
    
    public void setFechainicio(Date fechainicio) {
        this.fechainicio = fechainicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHAFIN", length=7)
    public Date getFechafin() {
        return this.fechafin;
    }
    
    public void setFechafin(Date fechafin) {
        this.fechafin = fechafin;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rgcSitdom")
    public Set<TepDomicilio> getTepDomicilios() {
        return this.tepDomicilios;
    }
    
    public void setTepDomicilios(Set<TepDomicilio> tepDomicilios) {
        this.tepDomicilios = tepDomicilios;
    }




}


