package reversedb.modelo2;
// Generated Jun 10, 2015 7:53:33 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SgcAdscripcion generated by hbm2java
 */
@Entity
@Table(name="SGC_ADSCRIPCION"
    ,schema="SIR7_ING"
)
public class SgcAdscripcion  implements java.io.Serializable {


     private BigDecimal claveadscripcion;
     private String nombre;
     private Date fechainicio;
     private Date fechafin;
     private BigDecimal clavetipoads;
     private Set<SgpOficina> sgpOficinas = new HashSet<SgpOficina>(0);

    public SgcAdscripcion() {
    }

	
    public SgcAdscripcion(BigDecimal claveadscripcion) {
        this.claveadscripcion = claveadscripcion;
    }
    public SgcAdscripcion(BigDecimal claveadscripcion, String nombre, Date fechainicio, Date fechafin, BigDecimal clavetipoads, Set<SgpOficina> sgpOficinas) {
       this.claveadscripcion = claveadscripcion;
       this.nombre = nombre;
       this.fechainicio = fechainicio;
       this.fechafin = fechafin;
       this.clavetipoads = clavetipoads;
       this.sgpOficinas = sgpOficinas;
    }
   
     @Id 

    
    @Column(name="CLAVEADSCRIPCION", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getClaveadscripcion() {
        return this.claveadscripcion;
    }
    
    public void setClaveadscripcion(BigDecimal claveadscripcion) {
        this.claveadscripcion = claveadscripcion;
    }

    
    @Column(name="NOMBRE", length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHAINICIO", length=7)
    public Date getFechainicio() {
        return this.fechainicio;
    }
    
    public void setFechainicio(Date fechainicio) {
        this.fechainicio = fechainicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHAFIN", length=7)
    public Date getFechafin() {
        return this.fechafin;
    }
    
    public void setFechafin(Date fechafin) {
        this.fechafin = fechafin;
    }

    
    @Column(name="CLAVETIPOADS", precision=22, scale=0)
    public BigDecimal getClavetipoads() {
        return this.clavetipoads;
    }
    
    public void setClavetipoads(BigDecimal clavetipoads) {
        this.clavetipoads = clavetipoads;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sgcAdscripcion")
    public Set<SgpOficina> getSgpOficinas() {
        return this.sgpOficinas;
    }
    
    public void setSgpOficinas(Set<SgpOficina> sgpOficinas) {
        this.sgpOficinas = sgpOficinas;
    }




}


