package reversedb.modelo2;
// Generated Jun 10, 2015 7:53:33 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * SgpUsuarios generated by hbm2java
 */
@Entity
@Table(name="SGP_USUARIOS"
    ,schema="SIR7_ING"
    , uniqueConstraints = @UniqueConstraint(columnNames="NOMBREUSUARIO") 
)
public class SgpUsuarios  implements java.io.Serializable {


     private BigDecimal claveusuario;
     private SgcTiposusuario sgcTiposusuario;
     private String nombreusuario;
     private String password;
     private BigDecimal estadousuario;
     private Date fecharegistro;
     private Date fechacambiopwd;
     private Date fechamovimiento;
     private int tipocambiopwd;
     private Boolean reintentos;
     private BigDecimal claveoficina;
     private Set<TetControlTramite> tetControlTramites = new HashSet<TetControlTramite>(0);

    public SgpUsuarios() {
    }

	
    public SgpUsuarios(BigDecimal claveusuario, String nombreusuario, String password, BigDecimal estadousuario, Date fecharegistro, int tipocambiopwd) {
        this.claveusuario = claveusuario;
        this.nombreusuario = nombreusuario;
        this.password = password;
        this.estadousuario = estadousuario;
        this.fecharegistro = fecharegistro;
        this.tipocambiopwd = tipocambiopwd;
    }
    public SgpUsuarios(BigDecimal claveusuario, SgcTiposusuario sgcTiposusuario, String nombreusuario, String password, BigDecimal estadousuario, Date fecharegistro, Date fechacambiopwd, Date fechamovimiento, int tipocambiopwd, Boolean reintentos, BigDecimal claveoficina, Set<TetControlTramite> tetControlTramites) {
       this.claveusuario = claveusuario;
       this.sgcTiposusuario = sgcTiposusuario;
       this.nombreusuario = nombreusuario;
       this.password = password;
       this.estadousuario = estadousuario;
       this.fecharegistro = fecharegistro;
       this.fechacambiopwd = fechacambiopwd;
       this.fechamovimiento = fechamovimiento;
       this.tipocambiopwd = tipocambiopwd;
       this.reintentos = reintentos;
       this.claveoficina = claveoficina;
       this.tetControlTramites = tetControlTramites;
    }
   
     @Id 

    
    @Column(name="CLAVEUSUARIO", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getClaveusuario() {
        return this.claveusuario;
    }
    
    public void setClaveusuario(BigDecimal claveusuario) {
        this.claveusuario = claveusuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TIPOUSUARIO")
    public SgcTiposusuario getSgcTiposusuario() {
        return this.sgcTiposusuario;
    }
    
    public void setSgcTiposusuario(SgcTiposusuario sgcTiposusuario) {
        this.sgcTiposusuario = sgcTiposusuario;
    }

    
    @Column(name="NOMBREUSUARIO", unique=true, nullable=false, length=50)
    public String getNombreusuario() {
        return this.nombreusuario;
    }
    
    public void setNombreusuario(String nombreusuario) {
        this.nombreusuario = nombreusuario;
    }

    
    @Column(name="PASSWORD", nullable=false, length=100)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="ESTADOUSUARIO", nullable=false, precision=22, scale=0)
    public BigDecimal getEstadousuario() {
        return this.estadousuario;
    }
    
    public void setEstadousuario(BigDecimal estadousuario) {
        this.estadousuario = estadousuario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHAREGISTRO", nullable=false, length=7)
    public Date getFecharegistro() {
        return this.fecharegistro;
    }
    
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHACAMBIOPWD", length=7)
    public Date getFechacambiopwd() {
        return this.fechacambiopwd;
    }
    
    public void setFechacambiopwd(Date fechacambiopwd) {
        this.fechacambiopwd = fechacambiopwd;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHAMOVIMIENTO", length=7)
    public Date getFechamovimiento() {
        return this.fechamovimiento;
    }
    
    public void setFechamovimiento(Date fechamovimiento) {
        this.fechamovimiento = fechamovimiento;
    }

    
    @Column(name="TIPOCAMBIOPWD", nullable=false, precision=5, scale=0)
    public int getTipocambiopwd() {
        return this.tipocambiopwd;
    }
    
    public void setTipocambiopwd(int tipocambiopwd) {
        this.tipocambiopwd = tipocambiopwd;
    }

    
    @Column(name="REINTENTOS", precision=1, scale=0)
    public Boolean getReintentos() {
        return this.reintentos;
    }
    
    public void setReintentos(Boolean reintentos) {
        this.reintentos = reintentos;
    }

    
    @Column(name="CLAVEOFICINA", precision=22, scale=0)
    public BigDecimal getClaveoficina() {
        return this.claveoficina;
    }
    
    public void setClaveoficina(BigDecimal claveoficina) {
        this.claveoficina = claveoficina;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sgpUsuarios")
    public Set<TetControlTramite> getTetControlTramites() {
        return this.tetControlTramites;
    }
    
    public void setTetControlTramites(Set<TetControlTramite> tetControlTramites) {
        this.tetControlTramites = tetControlTramites;
    }




}


