package reversedb.modelo2;
// Generated Jun 10, 2015 7:53:33 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TecCilindrosvehi generated by hbm2java
 */
@Entity
@Table(name="TEC_CILINDROSVEHI"
    ,schema="SIR7_ING"
)
public class TecCilindrosvehi  implements java.io.Serializable {


     private byte idCilindrosvehi;
     private String descripcionCilindrosvehi;
     private Date fechaAlta;
     private Date fechaBaja;
     private Set<TepVehiculo> tepVehiculos = new HashSet<TepVehiculo>(0);

    public TecCilindrosvehi() {
    }

	
    public TecCilindrosvehi(byte idCilindrosvehi, String descripcionCilindrosvehi, Date fechaAlta) {
        this.idCilindrosvehi = idCilindrosvehi;
        this.descripcionCilindrosvehi = descripcionCilindrosvehi;
        this.fechaAlta = fechaAlta;
    }
    public TecCilindrosvehi(byte idCilindrosvehi, String descripcionCilindrosvehi, Date fechaAlta, Date fechaBaja, Set<TepVehiculo> tepVehiculos) {
       this.idCilindrosvehi = idCilindrosvehi;
       this.descripcionCilindrosvehi = descripcionCilindrosvehi;
       this.fechaAlta = fechaAlta;
       this.fechaBaja = fechaBaja;
       this.tepVehiculos = tepVehiculos;
    }
   
     @Id 

    
    @Column(name="ID_CILINDROSVEHI", unique=true, nullable=false, precision=2, scale=0)
    public byte getIdCilindrosvehi() {
        return this.idCilindrosvehi;
    }
    
    public void setIdCilindrosvehi(byte idCilindrosvehi) {
        this.idCilindrosvehi = idCilindrosvehi;
    }

    
    @Column(name="DESCRIPCION_CILINDROSVEHI", nullable=false, length=2)
    public String getDescripcionCilindrosvehi() {
        return this.descripcionCilindrosvehi;
    }
    
    public void setDescripcionCilindrosvehi(String descripcionCilindrosvehi) {
        this.descripcionCilindrosvehi = descripcionCilindrosvehi;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_ALTA", nullable=false, length=7)
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_BAJA", length=7)
    public Date getFechaBaja() {
        return this.fechaBaja;
    }
    
    public void setFechaBaja(Date fechaBaja) {
        this.fechaBaja = fechaBaja;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tecCilindrosvehi")
    public Set<TepVehiculo> getTepVehiculos() {
        return this.tepVehiculos;
    }
    
    public void setTepVehiculos(Set<TepVehiculo> tepVehiculos) {
        this.tepVehiculos = tepVehiculos;
    }




}


