package reversedb.modelo2;
// Generated Jun 10, 2015 7:53:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TecEstadoimagenes generated by hbm2java
 */
@Entity
@Table(name="TEC_ESTADOIMAGENES"
    ,schema="SIR7_ING"
)
public class TecEstadoimagenes  implements java.io.Serializable {


     private byte idestadoimagen;
     private String estado;
     private Set<TetImagenes> tetImageneses = new HashSet<TetImagenes>(0);

    public TecEstadoimagenes() {
    }

	
    public TecEstadoimagenes(byte idestadoimagen) {
        this.idestadoimagen = idestadoimagen;
    }
    public TecEstadoimagenes(byte idestadoimagen, String estado, Set<TetImagenes> tetImageneses) {
       this.idestadoimagen = idestadoimagen;
       this.estado = estado;
       this.tetImageneses = tetImageneses;
    }
   
     @Id 

    
    @Column(name="IDESTADOIMAGEN", unique=true, nullable=false, precision=2, scale=0)
    public byte getIdestadoimagen() {
        return this.idestadoimagen;
    }
    
    public void setIdestadoimagen(byte idestadoimagen) {
        this.idestadoimagen = idestadoimagen;
    }

    
    @Column(name="ESTADO", length=50)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tecEstadoimagenes")
    public Set<TetImagenes> getTetImageneses() {
        return this.tetImageneses;
    }
    
    public void setTetImageneses(Set<TetImagenes> tetImageneses) {
        this.tetImageneses = tetImageneses;
    }




}


