package reversedb.modelo2;
// Generated Jun 10, 2015 7:53:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TecEstatusVehi generated by hbm2java
 */
@Entity
@Table(name="TEC_ESTATUS_VEHI"
    ,schema="SIR7_ING"
)
public class TecEstatusVehi  implements java.io.Serializable {


     private byte idEstatusVehi;
     private String descrip;
     private Set<TepVehiculo> tepVehiculos = new HashSet<TepVehiculo>(0);

    public TecEstatusVehi() {
    }

	
    public TecEstatusVehi(byte idEstatusVehi, String descrip) {
        this.idEstatusVehi = idEstatusVehi;
        this.descrip = descrip;
    }
    public TecEstatusVehi(byte idEstatusVehi, String descrip, Set<TepVehiculo> tepVehiculos) {
       this.idEstatusVehi = idEstatusVehi;
       this.descrip = descrip;
       this.tepVehiculos = tepVehiculos;
    }
   
     @Id 

    
    @Column(name="ID_ESTATUS_VEHI", unique=true, nullable=false, precision=2, scale=0)
    public byte getIdEstatusVehi() {
        return this.idEstatusVehi;
    }
    
    public void setIdEstatusVehi(byte idEstatusVehi) {
        this.idEstatusVehi = idEstatusVehi;
    }

    
    @Column(name="DESCRIP", nullable=false, length=25)
    public String getDescrip() {
        return this.descrip;
    }
    
    public void setDescrip(String descrip) {
        this.descrip = descrip;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tecEstatusVehi")
    public Set<TepVehiculo> getTepVehiculos() {
        return this.tepVehiculos;
    }
    
    public void setTepVehiculos(Set<TepVehiculo> tepVehiculos) {
        this.tepVehiculos = tepVehiculos;
    }




}


