package reversedb.modelo2;
// Generated Jun 10, 2015 7:53:33 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TecOpcrequisito generated by hbm2java
 */
@Entity
@Table(name="TEC_OPCREQUISITO"
    ,schema="SIR7_ING"
)
public class TecOpcrequisito  implements java.io.Serializable {


     private BigDecimal idTec;
     private String descrip;
     private String ayudas;
     private Date fecIniVig;
     private Date fecFinVig;
     private Set<TetImagenes> tetImageneses = new HashSet<TetImagenes>(0);

    public TecOpcrequisito() {
    }

	
    public TecOpcrequisito(BigDecimal idTec, String descrip) {
        this.idTec = idTec;
        this.descrip = descrip;
    }
    public TecOpcrequisito(BigDecimal idTec, String descrip, String ayudas, Date fecIniVig, Date fecFinVig, Set<TetImagenes> tetImageneses) {
       this.idTec = idTec;
       this.descrip = descrip;
       this.ayudas = ayudas;
       this.fecIniVig = fecIniVig;
       this.fecFinVig = fecFinVig;
       this.tetImageneses = tetImageneses;
    }
   
     @Id 

    
    @Column(name="ID_TEC", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdTec() {
        return this.idTec;
    }
    
    public void setIdTec(BigDecimal idTec) {
        this.idTec = idTec;
    }

    
    @Column(name="DESCRIP", nullable=false, length=250)
    public String getDescrip() {
        return this.descrip;
    }
    
    public void setDescrip(String descrip) {
        this.descrip = descrip;
    }

    
    @Column(name="AYUDAS", length=500)
    public String getAyudas() {
        return this.ayudas;
    }
    
    public void setAyudas(String ayudas) {
        this.ayudas = ayudas;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FEC_INI_VIG", length=7)
    public Date getFecIniVig() {
        return this.fecIniVig;
    }
    
    public void setFecIniVig(Date fecIniVig) {
        this.fecIniVig = fecIniVig;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FEC_FIN_VIG", length=7)
    public Date getFecFinVig() {
        return this.fecFinVig;
    }
    
    public void setFecFinVig(Date fecFinVig) {
        this.fecFinVig = fecFinVig;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tecOpcrequisito")
    public Set<TetImagenes> getTetImageneses() {
        return this.tetImageneses;
    }
    
    public void setTetImageneses(Set<TetImagenes> tetImageneses) {
        this.tetImageneses = tetImageneses;
    }




}


