package reversedb.modelo2;
// Generated Jun 10, 2015 7:53:33 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TecPasajerosvehi generated by hbm2java
 */
@Entity
@Table(name="TEC_PASAJEROSVEHI"
    ,schema="SIR7_ING"
)
public class TecPasajerosvehi  implements java.io.Serializable {


     private BigDecimal idPasajerosvehi;
     private byte descripcionPasavehi;
     private Date fechaAlta;
     private Date fechaBaja;
     private Set<TepVehiculo> tepVehiculos = new HashSet<TepVehiculo>(0);

    public TecPasajerosvehi() {
    }

	
    public TecPasajerosvehi(BigDecimal idPasajerosvehi, byte descripcionPasavehi, Date fechaAlta) {
        this.idPasajerosvehi = idPasajerosvehi;
        this.descripcionPasavehi = descripcionPasavehi;
        this.fechaAlta = fechaAlta;
    }
    public TecPasajerosvehi(BigDecimal idPasajerosvehi, byte descripcionPasavehi, Date fechaAlta, Date fechaBaja, Set<TepVehiculo> tepVehiculos) {
       this.idPasajerosvehi = idPasajerosvehi;
       this.descripcionPasavehi = descripcionPasavehi;
       this.fechaAlta = fechaAlta;
       this.fechaBaja = fechaBaja;
       this.tepVehiculos = tepVehiculos;
    }
   
     @Id 

    
    @Column(name="ID_PASAJEROSVEHI", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdPasajerosvehi() {
        return this.idPasajerosvehi;
    }
    
    public void setIdPasajerosvehi(BigDecimal idPasajerosvehi) {
        this.idPasajerosvehi = idPasajerosvehi;
    }

    
    @Column(name="DESCRIPCION_PASAVEHI", nullable=false, precision=2, scale=0)
    public byte getDescripcionPasavehi() {
        return this.descripcionPasavehi;
    }
    
    public void setDescripcionPasavehi(byte descripcionPasavehi) {
        this.descripcionPasavehi = descripcionPasavehi;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_ALTA", nullable=false, length=7)
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_BAJA", length=7)
    public Date getFechaBaja() {
        return this.fechaBaja;
    }
    
    public void setFechaBaja(Date fechaBaja) {
        this.fechaBaja = fechaBaja;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tecPasajerosvehi")
    public Set<TepVehiculo> getTepVehiculos() {
        return this.tepVehiculos;
    }
    
    public void setTepVehiculos(Set<TepVehiculo> tepVehiculos) {
        this.tepVehiculos = tepVehiculos;
    }




}


