package reversedb.modelo2;
// Generated Jun 10, 2015 7:53:33 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TecStatusCodigoseg generated by hbm2java
 */
@Entity
@Table(name="TEC_STATUS_CODIGOSEG"
    ,schema="SIR7_ING"
)
public class TecStatusCodigoseg  implements java.io.Serializable {


     private BigDecimal idEstadoCodigoSeguridad;
     private String descripcionStatCodseg;
     private Date fechaInicio;
     private Date fechaBaja;
     private Set<TetPrerequisitos> tetPrerequisitoses = new HashSet<TetPrerequisitos>(0);

    public TecStatusCodigoseg() {
    }

	
    public TecStatusCodigoseg(BigDecimal idEstadoCodigoSeguridad, String descripcionStatCodseg) {
        this.idEstadoCodigoSeguridad = idEstadoCodigoSeguridad;
        this.descripcionStatCodseg = descripcionStatCodseg;
    }
    public TecStatusCodigoseg(BigDecimal idEstadoCodigoSeguridad, String descripcionStatCodseg, Date fechaInicio, Date fechaBaja, Set<TetPrerequisitos> tetPrerequisitoses) {
       this.idEstadoCodigoSeguridad = idEstadoCodigoSeguridad;
       this.descripcionStatCodseg = descripcionStatCodseg;
       this.fechaInicio = fechaInicio;
       this.fechaBaja = fechaBaja;
       this.tetPrerequisitoses = tetPrerequisitoses;
    }
   
     @Id 

    
    @Column(name="ID_ESTADO_CODIGO_SEGURIDAD", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdEstadoCodigoSeguridad() {
        return this.idEstadoCodigoSeguridad;
    }
    
    public void setIdEstadoCodigoSeguridad(BigDecimal idEstadoCodigoSeguridad) {
        this.idEstadoCodigoSeguridad = idEstadoCodigoSeguridad;
    }

    
    @Column(name="DESCRIPCION_STAT_CODSEG", nullable=false, length=10)
    public String getDescripcionStatCodseg() {
        return this.descripcionStatCodseg;
    }
    
    public void setDescripcionStatCodseg(String descripcionStatCodseg) {
        this.descripcionStatCodseg = descripcionStatCodseg;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_INICIO", length=7)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_BAJA", length=7)
    public Date getFechaBaja() {
        return this.fechaBaja;
    }
    
    public void setFechaBaja(Date fechaBaja) {
        this.fechaBaja = fechaBaja;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tecStatusCodigoseg")
    public Set<TetPrerequisitos> getTetPrerequisitoses() {
        return this.tetPrerequisitoses;
    }
    
    public void setTetPrerequisitoses(Set<TetPrerequisitos> tetPrerequisitoses) {
        this.tetPrerequisitoses = tetPrerequisitoses;
    }




}


