package reversedb.modelo2;
// Generated Jun 10, 2015 7:53:33 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TecTipoconclusion generated by hbm2java
 */
@Entity
@Table(name="TEC_TIPOCONCLUSION"
    ,schema="SIR7_ING"
)
public class TecTipoconclusion  implements java.io.Serializable {


     private BigDecimal idConclusion;
     private String descrip;
     private Date fecAlta;
     private Date fecBaja;
     private Set<TetControlTramite> tetControlTramites = new HashSet<TetControlTramite>(0);

    public TecTipoconclusion() {
    }

	
    public TecTipoconclusion(BigDecimal idConclusion, String descrip, Date fecAlta) {
        this.idConclusion = idConclusion;
        this.descrip = descrip;
        this.fecAlta = fecAlta;
    }
    public TecTipoconclusion(BigDecimal idConclusion, String descrip, Date fecAlta, Date fecBaja, Set<TetControlTramite> tetControlTramites) {
       this.idConclusion = idConclusion;
       this.descrip = descrip;
       this.fecAlta = fecAlta;
       this.fecBaja = fecBaja;
       this.tetControlTramites = tetControlTramites;
    }
   
     @Id 

    
    @Column(name="ID_CONCLUSION", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdConclusion() {
        return this.idConclusion;
    }
    
    public void setIdConclusion(BigDecimal idConclusion) {
        this.idConclusion = idConclusion;
    }

    
    @Column(name="DESCRIP", nullable=false, length=25)
    public String getDescrip() {
        return this.descrip;
    }
    
    public void setDescrip(String descrip) {
        this.descrip = descrip;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FEC_ALTA", nullable=false, length=7)
    public Date getFecAlta() {
        return this.fecAlta;
    }
    
    public void setFecAlta(Date fecAlta) {
        this.fecAlta = fecAlta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FEC_BAJA", length=7)
    public Date getFecBaja() {
        return this.fecBaja;
    }
    
    public void setFecBaja(Date fecBaja) {
        this.fecBaja = fecBaja;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tecTipoconclusion")
    public Set<TetControlTramite> getTetControlTramites() {
        return this.tetControlTramites;
    }
    
    public void setTetControlTramites(Set<TetControlTramite> tetControlTramites) {
        this.tetControlTramites = tetControlTramites;
    }




}


