package reversedb.modelo2;
// Generated Jun 10, 2015 7:53:33 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TecVincesvi generated by hbm2java
 */
@Entity
@Table(name="TEC_VINCESVI"
    ,schema="SIR7_ING"
)
public class TecVincesvi  implements java.io.Serializable {


     private byte idtipovehiculo;
     private String descripcion;
     private Date fechaAlta;
     private Date fechaBaja;
     private Set<TetControlTramite> tetControlTramites = new HashSet<TetControlTramite>(0);

    public TecVincesvi() {
    }

	
    public TecVincesvi(byte idtipovehiculo) {
        this.idtipovehiculo = idtipovehiculo;
    }
    public TecVincesvi(byte idtipovehiculo, String descripcion, Date fechaAlta, Date fechaBaja, Set<TetControlTramite> tetControlTramites) {
       this.idtipovehiculo = idtipovehiculo;
       this.descripcion = descripcion;
       this.fechaAlta = fechaAlta;
       this.fechaBaja = fechaBaja;
       this.tetControlTramites = tetControlTramites;
    }
   
     @Id 

    
    @Column(name="IDTIPOVEHICULO", unique=true, nullable=false, precision=2, scale=0)
    public byte getIdtipovehiculo() {
        return this.idtipovehiculo;
    }
    
    public void setIdtipovehiculo(byte idtipovehiculo) {
        this.idtipovehiculo = idtipovehiculo;
    }

    
    @Column(name="DESCRIPCION", length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_ALTA", length=7)
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_BAJA", length=7)
    public Date getFechaBaja() {
        return this.fechaBaja;
    }
    
    public void setFechaBaja(Date fechaBaja) {
        this.fechaBaja = fechaBaja;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tecVincesvi")
    public Set<TetControlTramite> getTetControlTramites() {
        return this.tetControlTramites;
    }
    
    public void setTetControlTramites(Set<TetControlTramite> tetControlTramites) {
        this.tetControlTramites = tetControlTramites;
    }




}


