package reversedb.modelo2;
// Generated Jun 10, 2015 7:53:33 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TepContribuyente generated by hbm2java
 */
@Entity
@Table(name="TEP_CONTRIBUYENTE"
    ,schema="SIR7_ING"
)
public class TepContribuyente  implements java.io.Serializable {


     private BigDecimal idContribuyente;
     private RgcSitcont rgcSitcont;
     private TepDomicilio tepDomicilio;
     private TecTipocont tecTipocont;
     private String rfc;
     private Set<TetControlTramite> tetControlTramites = new HashSet<TetControlTramite>(0);

    public TepContribuyente() {
    }

	
    public TepContribuyente(BigDecimal idContribuyente, RgcSitcont rgcSitcont, TepDomicilio tepDomicilio, TecTipocont tecTipocont, String rfc) {
        this.idContribuyente = idContribuyente;
        this.rgcSitcont = rgcSitcont;
        this.tepDomicilio = tepDomicilio;
        this.tecTipocont = tecTipocont;
        this.rfc = rfc;
    }
    public TepContribuyente(BigDecimal idContribuyente, RgcSitcont rgcSitcont, TepDomicilio tepDomicilio, TecTipocont tecTipocont, String rfc, Set<TetControlTramite> tetControlTramites) {
       this.idContribuyente = idContribuyente;
       this.rgcSitcont = rgcSitcont;
       this.tepDomicilio = tepDomicilio;
       this.tecTipocont = tecTipocont;
       this.rfc = rfc;
       this.tetControlTramites = tetControlTramites;
    }
   
     @Id 

    
    @Column(name="ID_CONTRIBUYENTE", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdContribuyente() {
        return this.idContribuyente;
    }
    
    public void setIdContribuyente(BigDecimal idContribuyente) {
        this.idContribuyente = idContribuyente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLAVESITCONT", nullable=false)
    public RgcSitcont getRgcSitcont() {
        return this.rgcSitcont;
    }
    
    public void setRgcSitcont(RgcSitcont rgcSitcont) {
        this.rgcSitcont = rgcSitcont;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLAVEDOM", nullable=false)
    public TepDomicilio getTepDomicilio() {
        return this.tepDomicilio;
    }
    
    public void setTepDomicilio(TepDomicilio tepDomicilio) {
        this.tepDomicilio = tepDomicilio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLAVETIPOCONT", nullable=false)
    public TecTipocont getTecTipocont() {
        return this.tecTipocont;
    }
    
    public void setTecTipocont(TecTipocont tecTipocont) {
        this.tecTipocont = tecTipocont;
    }

    
    @Column(name="RFC", nullable=false, length=13)
    public String getRfc() {
        return this.rfc;
    }
    
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tepContribuyente")
    public Set<TetControlTramite> getTetControlTramites() {
        return this.tetControlTramites;
    }
    
    public void setTetControlTramites(Set<TetControlTramite> tetControlTramites) {
        this.tetControlTramites = tetControlTramites;
    }




}


