package reversedb.modelo2;
// Generated Jun 10, 2015 7:53:33 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TepVehiculo generated by hbm2java
 */
@Entity
@Table(name="TEP_VEHICULO"
    ,schema="SIR7_ING"
)
public class TepVehiculo  implements java.io.Serializable {


     private String serieVehi;
     private CvcTransmisionRepuve cvcTransmisionRepuve;
     private CvcCombustibleRepuve cvcCombustibleRepuve;
     private CvcUsoVehiRepuve cvcUsoVehiRepuve;
     private CvcTipoVehiRepuve cvcTipoVehiRepuve;
     private CvcClaseVehiRepuve cvcClaseVehiRepuve;
     private CvcColorvehi cvcColorvehi;
     private CvcPaisorigen cvcPaisorigen;
     private TecCilindrosvehi tecCilindrosvehi;
     private TecPasajerosvehi tecPasajerosvehi;
     private TecEstatusVehi tecEstatusVehi;
     private String cveVehi;
     private String modeloVehi;
     private String verVehi;
     private String marVehi;
     private String claseVehi;
     private String tipoVehi;
     private String puertasVehi;
     private BigDecimal ccmotoVehi;
     private BigDecimal ccCarga;
     private String aniomodeloVehi;
     private String nrpv;
     private String numMotor;
     private String factura;
     private Date fechafactura;
     private BigDecimal importeFactura;
     private Set<TetControlTramite> tetControlTramites = new HashSet<TetControlTramite>(0);

    public TepVehiculo() {
    }

	
    public TepVehiculo(String serieVehi) {
        this.serieVehi = serieVehi;
    }
    public TepVehiculo(String serieVehi, CvcTransmisionRepuve cvcTransmisionRepuve, CvcCombustibleRepuve cvcCombustibleRepuve, CvcUsoVehiRepuve cvcUsoVehiRepuve, CvcTipoVehiRepuve cvcTipoVehiRepuve, CvcClaseVehiRepuve cvcClaseVehiRepuve, CvcColorvehi cvcColorvehi, CvcPaisorigen cvcPaisorigen, TecCilindrosvehi tecCilindrosvehi, TecPasajerosvehi tecPasajerosvehi, TecEstatusVehi tecEstatusVehi, String cveVehi, String modeloVehi, String verVehi, String marVehi, String claseVehi, String tipoVehi, String puertasVehi, BigDecimal ccmotoVehi, BigDecimal ccCarga, String aniomodeloVehi, String nrpv, String numMotor, String factura, Date fechafactura, BigDecimal importeFactura, Set<TetControlTramite> tetControlTramites) {
       this.serieVehi = serieVehi;
       this.cvcTransmisionRepuve = cvcTransmisionRepuve;
       this.cvcCombustibleRepuve = cvcCombustibleRepuve;
       this.cvcUsoVehiRepuve = cvcUsoVehiRepuve;
       this.cvcTipoVehiRepuve = cvcTipoVehiRepuve;
       this.cvcClaseVehiRepuve = cvcClaseVehiRepuve;
       this.cvcColorvehi = cvcColorvehi;
       this.cvcPaisorigen = cvcPaisorigen;
       this.tecCilindrosvehi = tecCilindrosvehi;
       this.tecPasajerosvehi = tecPasajerosvehi;
       this.tecEstatusVehi = tecEstatusVehi;
       this.cveVehi = cveVehi;
       this.modeloVehi = modeloVehi;
       this.verVehi = verVehi;
       this.marVehi = marVehi;
       this.claseVehi = claseVehi;
       this.tipoVehi = tipoVehi;
       this.puertasVehi = puertasVehi;
       this.ccmotoVehi = ccmotoVehi;
       this.ccCarga = ccCarga;
       this.aniomodeloVehi = aniomodeloVehi;
       this.nrpv = nrpv;
       this.numMotor = numMotor;
       this.factura = factura;
       this.fechafactura = fechafactura;
       this.importeFactura = importeFactura;
       this.tetControlTramites = tetControlTramites;
    }
   
     @Id 

    
    @Column(name="SERIE_VEHI", unique=true, nullable=false, length=17)
    public String getSerieVehi() {
        return this.serieVehi;
    }
    
    public void setSerieVehi(String serieVehi) {
        this.serieVehi = serieVehi;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_TRANSMISION")
    public CvcTransmisionRepuve getCvcTransmisionRepuve() {
        return this.cvcTransmisionRepuve;
    }
    
    public void setCvcTransmisionRepuve(CvcTransmisionRepuve cvcTransmisionRepuve) {
        this.cvcTransmisionRepuve = cvcTransmisionRepuve;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_COMBUSTIBLE")
    public CvcCombustibleRepuve getCvcCombustibleRepuve() {
        return this.cvcCombustibleRepuve;
    }
    
    public void setCvcCombustibleRepuve(CvcCombustibleRepuve cvcCombustibleRepuve) {
        this.cvcCombustibleRepuve = cvcCombustibleRepuve;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_USO_VEHI")
    public CvcUsoVehiRepuve getCvcUsoVehiRepuve() {
        return this.cvcUsoVehiRepuve;
    }
    
    public void setCvcUsoVehiRepuve(CvcUsoVehiRepuve cvcUsoVehiRepuve) {
        this.cvcUsoVehiRepuve = cvcUsoVehiRepuve;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="ID_CLASE_VEHI", referencedColumnName="ID_CLASE_VEHI"), 
        @JoinColumn(name="ID_TIPO_VEHI", referencedColumnName="ID_TIPO_VEHI") } )
    public CvcTipoVehiRepuve getCvcTipoVehiRepuve() {
        return this.cvcTipoVehiRepuve;
    }
    
    public void setCvcTipoVehiRepuve(CvcTipoVehiRepuve cvcTipoVehiRepuve) {
        this.cvcTipoVehiRepuve = cvcTipoVehiRepuve;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_CLASE_VEHI", insertable=false, updatable=false)
    public CvcClaseVehiRepuve getCvcClaseVehiRepuve() {
        return this.cvcClaseVehiRepuve;
    }
    
    public void setCvcClaseVehiRepuve(CvcClaseVehiRepuve cvcClaseVehiRepuve) {
        this.cvcClaseVehiRepuve = cvcClaseVehiRepuve;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLAVECOLOR")
    public CvcColorvehi getCvcColorvehi() {
        return this.cvcColorvehi;
    }
    
    public void setCvcColorvehi(CvcColorvehi cvcColorvehi) {
        this.cvcColorvehi = cvcColorvehi;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PAIS_ORIGEN")
    public CvcPaisorigen getCvcPaisorigen() {
        return this.cvcPaisorigen;
    }
    
    public void setCvcPaisorigen(CvcPaisorigen cvcPaisorigen) {
        this.cvcPaisorigen = cvcPaisorigen;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_CILINDROSVEHI")
    public TecCilindrosvehi getTecCilindrosvehi() {
        return this.tecCilindrosvehi;
    }
    
    public void setTecCilindrosvehi(TecCilindrosvehi tecCilindrosvehi) {
        this.tecCilindrosvehi = tecCilindrosvehi;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PASAJEROSVEHI")
    public TecPasajerosvehi getTecPasajerosvehi() {
        return this.tecPasajerosvehi;
    }
    
    public void setTecPasajerosvehi(TecPasajerosvehi tecPasajerosvehi) {
        this.tecPasajerosvehi = tecPasajerosvehi;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ESTATUS_VEHI")
    public TecEstatusVehi getTecEstatusVehi() {
        return this.tecEstatusVehi;
    }
    
    public void setTecEstatusVehi(TecEstatusVehi tecEstatusVehi) {
        this.tecEstatusVehi = tecEstatusVehi;
    }

    
    @Column(name="CVE_VEHI", length=7)
    public String getCveVehi() {
        return this.cveVehi;
    }
    
    public void setCveVehi(String cveVehi) {
        this.cveVehi = cveVehi;
    }

    
    @Column(name="MODELO_VEHI", length=100)
    public String getModeloVehi() {
        return this.modeloVehi;
    }
    
    public void setModeloVehi(String modeloVehi) {
        this.modeloVehi = modeloVehi;
    }

    
    @Column(name="VER_VEHI", length=100)
    public String getVerVehi() {
        return this.verVehi;
    }
    
    public void setVerVehi(String verVehi) {
        this.verVehi = verVehi;
    }

    
    @Column(name="MAR_VEHI", length=50)
    public String getMarVehi() {
        return this.marVehi;
    }
    
    public void setMarVehi(String marVehi) {
        this.marVehi = marVehi;
    }

    
    @Column(name="CLASE_VEHI", length=10)
    public String getClaseVehi() {
        return this.claseVehi;
    }
    
    public void setClaseVehi(String claseVehi) {
        this.claseVehi = claseVehi;
    }

    
    @Column(name="TIPO_VEHI", length=2)
    public String getTipoVehi() {
        return this.tipoVehi;
    }
    
    public void setTipoVehi(String tipoVehi) {
        this.tipoVehi = tipoVehi;
    }

    
    @Column(name="PUERTAS_VEHI", length=1)
    public String getPuertasVehi() {
        return this.puertasVehi;
    }
    
    public void setPuertasVehi(String puertasVehi) {
        this.puertasVehi = puertasVehi;
    }

    
    @Column(name="CCMOTO_VEHI", precision=22, scale=0)
    public BigDecimal getCcmotoVehi() {
        return this.ccmotoVehi;
    }
    
    public void setCcmotoVehi(BigDecimal ccmotoVehi) {
        this.ccmotoVehi = ccmotoVehi;
    }

    
    @Column(name="CC_CARGA", precision=22, scale=0)
    public BigDecimal getCcCarga() {
        return this.ccCarga;
    }
    
    public void setCcCarga(BigDecimal ccCarga) {
        this.ccCarga = ccCarga;
    }

    
    @Column(name="ANIOMODELO_VEHI", length=4)
    public String getAniomodeloVehi() {
        return this.aniomodeloVehi;
    }
    
    public void setAniomodeloVehi(String aniomodeloVehi) {
        this.aniomodeloVehi = aniomodeloVehi;
    }

    
    @Column(name="NRPV", length=8)
    public String getNrpv() {
        return this.nrpv;
    }
    
    public void setNrpv(String nrpv) {
        this.nrpv = nrpv;
    }

    
    @Column(name="NUM_MOTOR", length=30)
    public String getNumMotor() {
        return this.numMotor;
    }
    
    public void setNumMotor(String numMotor) {
        this.numMotor = numMotor;
    }

    
    @Column(name="FACTURA", length=20)
    public String getFactura() {
        return this.factura;
    }
    
    public void setFactura(String factura) {
        this.factura = factura;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHAFACTURA", length=7)
    public Date getFechafactura() {
        return this.fechafactura;
    }
    
    public void setFechafactura(Date fechafactura) {
        this.fechafactura = fechafactura;
    }

    
    @Column(name="IMPORTE_FACTURA", precision=16)
    public BigDecimal getImporteFactura() {
        return this.importeFactura;
    }
    
    public void setImporteFactura(BigDecimal importeFactura) {
        this.importeFactura = importeFactura;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tepVehiculo")
    public Set<TetControlTramite> getTetControlTramites() {
        return this.tetControlTramites;
    }
    
    public void setTetControlTramites(Set<TetControlTramite> tetControlTramites) {
        this.tetControlTramites = tetControlTramites;
    }




}


