package reversedb.modelo2;
// Generated Jun 10, 2015 7:53:33 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TetControlTramite generated by hbm2java
 */
@Entity
@Table(name="TET_CONTROL_TRAMITE"
    ,schema="SIR7_ING"
)
public class TetControlTramite  implements java.io.Serializable {


     private long folioConsecutivo;
     private TepVehiculo tepVehiculo;
     private TetPrerequisitos tetPrerequisitos;
     private CvcMotivobajas cvcMotivobajas;
     private SgpUsuarios sgpUsuarios;
     private CvcTipoplacaweb cvcTipoplacaweb;
     private SgpOficina sgpOficina;
     private ItServicios itServicios;
     private TecEstatustramite tecEstatustramite;
     private TecTipoconclusion tecTipoconclusion;
     private TecVincesvi tecVincesvi;
     private TepContribuyente tepContribuyente;
     private Serializable fechaIniciotramite;
     private Serializable fechaConclusiontramite;
     private String observaciones;
     private String referenciaTramitecv;
     private char prioridad;

    public TetControlTramite() {
    }

	
    public TetControlTramite(long folioConsecutivo, TetPrerequisitos tetPrerequisitos, SgpOficina sgpOficina, TecEstatustramite tecEstatustramite, TepContribuyente tepContribuyente, char prioridad) {
        this.folioConsecutivo = folioConsecutivo;
        this.tetPrerequisitos = tetPrerequisitos;
        this.sgpOficina = sgpOficina;
        this.tecEstatustramite = tecEstatustramite;
        this.tepContribuyente = tepContribuyente;
        this.prioridad = prioridad;
    }
    public TetControlTramite(long folioConsecutivo, TepVehiculo tepVehiculo, TetPrerequisitos tetPrerequisitos, CvcMotivobajas cvcMotivobajas, SgpUsuarios sgpUsuarios, CvcTipoplacaweb cvcTipoplacaweb, SgpOficina sgpOficina, ItServicios itServicios, TecEstatustramite tecEstatustramite, TecTipoconclusion tecTipoconclusion, TecVincesvi tecVincesvi, TepContribuyente tepContribuyente, Serializable fechaIniciotramite, Serializable fechaConclusiontramite, String observaciones, String referenciaTramitecv, char prioridad) {
       this.folioConsecutivo = folioConsecutivo;
       this.tepVehiculo = tepVehiculo;
       this.tetPrerequisitos = tetPrerequisitos;
       this.cvcMotivobajas = cvcMotivobajas;
       this.sgpUsuarios = sgpUsuarios;
       this.cvcTipoplacaweb = cvcTipoplacaweb;
       this.sgpOficina = sgpOficina;
       this.itServicios = itServicios;
       this.tecEstatustramite = tecEstatustramite;
       this.tecTipoconclusion = tecTipoconclusion;
       this.tecVincesvi = tecVincesvi;
       this.tepContribuyente = tepContribuyente;
       this.fechaIniciotramite = fechaIniciotramite;
       this.fechaConclusiontramite = fechaConclusiontramite;
       this.observaciones = observaciones;
       this.referenciaTramitecv = referenciaTramitecv;
       this.prioridad = prioridad;
    }
   
     @Id 

    
    @Column(name="FOLIO_CONSECUTIVO", unique=true, nullable=false, precision=12, scale=0)
    public long getFolioConsecutivo() {
        return this.folioConsecutivo;
    }
    
    public void setFolioConsecutivo(long folioConsecutivo) {
        this.folioConsecutivo = folioConsecutivo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SERIE_VEHI")
    public TepVehiculo getTepVehiculo() {
        return this.tepVehiculo;
    }
    
    public void setTepVehiculo(TepVehiculo tepVehiculo) {
        this.tepVehiculo = tepVehiculo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PREREQUISITO", nullable=false)
    public TetPrerequisitos getTetPrerequisitos() {
        return this.tetPrerequisitos;
    }
    
    public void setTetPrerequisitos(TetPrerequisitos tetPrerequisitos) {
        this.tetPrerequisitos = tetPrerequisitos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_MOTIVOBAJA")
    public CvcMotivobajas getCvcMotivobajas() {
        return this.cvcMotivobajas;
    }
    
    public void setCvcMotivobajas(CvcMotivobajas cvcMotivobajas) {
        this.cvcMotivobajas = cvcMotivobajas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLAVEUSUARIO")
    public SgpUsuarios getSgpUsuarios() {
        return this.sgpUsuarios;
    }
    
    public void setSgpUsuarios(SgpUsuarios sgpUsuarios) {
        this.sgpUsuarios = sgpUsuarios;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TIPO_PLACA")
    public CvcTipoplacaweb getCvcTipoplacaweb() {
        return this.cvcTipoplacaweb;
    }
    
    public void setCvcTipoplacaweb(CvcTipoplacaweb cvcTipoplacaweb) {
        this.cvcTipoplacaweb = cvcTipoplacaweb;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLAVEOFICINA", nullable=false)
    public SgpOficina getSgpOficina() {
        return this.sgpOficina;
    }
    
    public void setSgpOficina(SgpOficina sgpOficina) {
        this.sgpOficina = sgpOficina;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="CLAVEOPERACIONSERV", referencedColumnName="CLAVEOPERACIONSERV"), 
        @JoinColumn(name="CLAVEPERIODO", referencedColumnName="CLAVEPERIODO") } )
    public ItServicios getItServicios() {
        return this.itServicios;
    }
    
    public void setItServicios(ItServicios itServicios) {
        this.itServicios = itServicios;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDESTATUSTRAMITE", nullable=false)
    public TecEstatustramite getTecEstatustramite() {
        return this.tecEstatustramite;
    }
    
    public void setTecEstatustramite(TecEstatustramite tecEstatustramite) {
        this.tecEstatustramite = tecEstatustramite;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_CONCLUSION")
    public TecTipoconclusion getTecTipoconclusion() {
        return this.tecTipoconclusion;
    }
    
    public void setTecTipoconclusion(TecTipoconclusion tecTipoconclusion) {
        this.tecTipoconclusion = tecTipoconclusion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDTIPOVEHICULO")
    public TecVincesvi getTecVincesvi() {
        return this.tecVincesvi;
    }
    
    public void setTecVincesvi(TecVincesvi tecVincesvi) {
        this.tecVincesvi = tecVincesvi;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_CONTRIBUYENTE", nullable=false)
    public TepContribuyente getTepContribuyente() {
        return this.tepContribuyente;
    }
    
    public void setTepContribuyente(TepContribuyente tepContribuyente) {
        this.tepContribuyente = tepContribuyente;
    }

    
    @Column(name="FECHA_INICIOTRAMITE")
    public Serializable getFechaIniciotramite() {
        return this.fechaIniciotramite;
    }
    
    public void setFechaIniciotramite(Serializable fechaIniciotramite) {
        this.fechaIniciotramite = fechaIniciotramite;
    }

    
    @Column(name="FECHA_CONCLUSIONTRAMITE")
    public Serializable getFechaConclusiontramite() {
        return this.fechaConclusiontramite;
    }
    
    public void setFechaConclusiontramite(Serializable fechaConclusiontramite) {
        this.fechaConclusiontramite = fechaConclusiontramite;
    }

    
    @Column(name="OBSERVACIONES", length=1000)
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    
    @Column(name="REFERENCIA_TRAMITECV", length=15)
    public String getReferenciaTramitecv() {
        return this.referenciaTramitecv;
    }
    
    public void setReferenciaTramitecv(String referenciaTramitecv) {
        this.referenciaTramitecv = referenciaTramitecv;
    }

    
    @Column(name="PRIORIDAD", nullable=false, length=1)
    public char getPrioridad() {
        return this.prioridad;
    }
    
    public void setPrioridad(char prioridad) {
        this.prioridad = prioridad;
    }




}


