package reversedb.modelo2;
// Generated Jun 10, 2015 7:53:33 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Blob;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TetImagenes generated by hbm2java
 */
@Entity
@Table(name="TET_IMAGENES"
    ,schema="SIR7_ING"
)
public class TetImagenes  implements java.io.Serializable {


     private BigDecimal idImagen;
     private TecEstadoimagenes tecEstadoimagenes;
     private TecOpcrequisito tecOpcrequisito;
     private TetPrerequisitos tetPrerequisitos;
     private CvcRequisitos cvcRequisitos;
     private String nombrearchivo;
     private Blob archivo;
     private Byte consecutivoimg;
     private String observaciones;

    public TetImagenes() {
    }

	
    public TetImagenes(BigDecimal idImagen, TetPrerequisitos tetPrerequisitos, CvcRequisitos cvcRequisitos, String nombrearchivo, Blob archivo) {
        this.idImagen = idImagen;
        this.tetPrerequisitos = tetPrerequisitos;
        this.cvcRequisitos = cvcRequisitos;
        this.nombrearchivo = nombrearchivo;
        this.archivo = archivo;
    }
    public TetImagenes(BigDecimal idImagen, TecEstadoimagenes tecEstadoimagenes, TecOpcrequisito tecOpcrequisito, TetPrerequisitos tetPrerequisitos, CvcRequisitos cvcRequisitos, String nombrearchivo, Blob archivo, Byte consecutivoimg, String observaciones) {
       this.idImagen = idImagen;
       this.tecEstadoimagenes = tecEstadoimagenes;
       this.tecOpcrequisito = tecOpcrequisito;
       this.tetPrerequisitos = tetPrerequisitos;
       this.cvcRequisitos = cvcRequisitos;
       this.nombrearchivo = nombrearchivo;
       this.archivo = archivo;
       this.consecutivoimg = consecutivoimg;
       this.observaciones = observaciones;
    }
   
     @Id 

    
    @Column(name="ID_IMAGEN", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdImagen() {
        return this.idImagen;
    }
    
    public void setIdImagen(BigDecimal idImagen) {
        this.idImagen = idImagen;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDESTADOIMAGEN")
    public TecEstadoimagenes getTecEstadoimagenes() {
        return this.tecEstadoimagenes;
    }
    
    public void setTecEstadoimagenes(TecEstadoimagenes tecEstadoimagenes) {
        this.tecEstadoimagenes = tecEstadoimagenes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_TEC")
    public TecOpcrequisito getTecOpcrequisito() {
        return this.tecOpcrequisito;
    }
    
    public void setTecOpcrequisito(TecOpcrequisito tecOpcrequisito) {
        this.tecOpcrequisito = tecOpcrequisito;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PREREQUISITO", nullable=false)
    public TetPrerequisitos getTetPrerequisitos() {
        return this.tetPrerequisitos;
    }
    
    public void setTetPrerequisitos(TetPrerequisitos tetPrerequisitos) {
        this.tetPrerequisitos = tetPrerequisitos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLAVEREQUISITO", nullable=false)
    public CvcRequisitos getCvcRequisitos() {
        return this.cvcRequisitos;
    }
    
    public void setCvcRequisitos(CvcRequisitos cvcRequisitos) {
        this.cvcRequisitos = cvcRequisitos;
    }

    
    @Column(name="NOMBREARCHIVO", nullable=false, length=80)
    public String getNombrearchivo() {
        return this.nombrearchivo;
    }
    
    public void setNombrearchivo(String nombrearchivo) {
        this.nombrearchivo = nombrearchivo;
    }

    
    @Column(name="ARCHIVO", nullable=false)
    public Blob getArchivo() {
        return this.archivo;
    }
    
    public void setArchivo(Blob archivo) {
        this.archivo = archivo;
    }

    
    @Column(name="CONSECUTIVOIMG", precision=2, scale=0)
    public Byte getConsecutivoimg() {
        return this.consecutivoimg;
    }
    
    public void setConsecutivoimg(Byte consecutivoimg) {
        this.consecutivoimg = consecutivoimg;
    }

    
    @Column(name="OBSERVACIONES", length=700)
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }




}


