package reversedb.modelo2;
// Generated Jun 10, 2015 7:53:33 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TetPrerequisitos generated by hbm2java
 */
@Entity
@Table(name="TET_PREREQUISITOS"
    ,schema="SIR7_ING"
    , uniqueConstraints = @UniqueConstraint(columnNames="CODIGO_SEGURIDAD") 
)
public class TetPrerequisitos  implements java.io.Serializable {


     private BigDecimal idPrerequisito;
     private TecStatusCodigoseg tecStatusCodigoseg;
     private short anioGenera;
     private String idMovto;
     private String correoElectronico;
     private String codigoSeguridad;
     private Set<TetImagenes> tetImageneses = new HashSet<TetImagenes>(0);
     private Set<TetControlTramite> tetControlTramites = new HashSet<TetControlTramite>(0);

    public TetPrerequisitos() {
    }

	
    public TetPrerequisitos(BigDecimal idPrerequisito, TecStatusCodigoseg tecStatusCodigoseg, short anioGenera, String idMovto, String correoElectronico, String codigoSeguridad) {
        this.idPrerequisito = idPrerequisito;
        this.tecStatusCodigoseg = tecStatusCodigoseg;
        this.anioGenera = anioGenera;
        this.idMovto = idMovto;
        this.correoElectronico = correoElectronico;
        this.codigoSeguridad = codigoSeguridad;
    }
    public TetPrerequisitos(BigDecimal idPrerequisito, TecStatusCodigoseg tecStatusCodigoseg, short anioGenera, String idMovto, String correoElectronico, String codigoSeguridad, Set<TetImagenes> tetImageneses, Set<TetControlTramite> tetControlTramites) {
       this.idPrerequisito = idPrerequisito;
       this.tecStatusCodigoseg = tecStatusCodigoseg;
       this.anioGenera = anioGenera;
       this.idMovto = idMovto;
       this.correoElectronico = correoElectronico;
       this.codigoSeguridad = codigoSeguridad;
       this.tetImageneses = tetImageneses;
       this.tetControlTramites = tetControlTramites;
    }
   
     @Id 

    
    @Column(name="ID_PREREQUISITO", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdPrerequisito() {
        return this.idPrerequisito;
    }
    
    public void setIdPrerequisito(BigDecimal idPrerequisito) {
        this.idPrerequisito = idPrerequisito;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ESTADO_CODIGO_SEGURIDAD", nullable=false)
    public TecStatusCodigoseg getTecStatusCodigoseg() {
        return this.tecStatusCodigoseg;
    }
    
    public void setTecStatusCodigoseg(TecStatusCodigoseg tecStatusCodigoseg) {
        this.tecStatusCodigoseg = tecStatusCodigoseg;
    }

    
    @Column(name="ANIO_GENERA", nullable=false, precision=4, scale=0)
    public short getAnioGenera() {
        return this.anioGenera;
    }
    
    public void setAnioGenera(short anioGenera) {
        this.anioGenera = anioGenera;
    }

    
    @Column(name="ID_MOVTO", nullable=false, length=3)
    public String getIdMovto() {
        return this.idMovto;
    }
    
    public void setIdMovto(String idMovto) {
        this.idMovto = idMovto;
    }

    
    @Column(name="CORREO_ELECTRONICO", nullable=false, length=50)
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }

    
    @Column(name="CODIGO_SEGURIDAD", unique=true, nullable=false, length=12)
    public String getCodigoSeguridad() {
        return this.codigoSeguridad;
    }
    
    public void setCodigoSeguridad(String codigoSeguridad) {
        this.codigoSeguridad = codigoSeguridad;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tetPrerequisitos")
    public Set<TetImagenes> getTetImageneses() {
        return this.tetImageneses;
    }
    
    public void setTetImageneses(Set<TetImagenes> tetImageneses) {
        this.tetImageneses = tetImageneses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tetPrerequisitos")
    public Set<TetControlTramite> getTetControlTramites() {
        return this.tetControlTramites;
    }
    
    public void setTetControlTramites(Set<TetControlTramite> tetControlTramites) {
        this.tetControlTramites = tetControlTramites;
    }




}


