package reversedb.simple;
// Generated Jun 10, 2015 7:53:33 PM by Hibernate Tools 4.3.1


import reversedb.modelo2.*;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TecEstadoimagenes generated by hbm2java
 */
@Entity
@Table(name="TEC_ESTADOIMAGENES"
)
public class TecEstadoimagenesSimple  implements java.io.Serializable {


     private byte idestadoimagen;
     private String estado;

    public TecEstadoimagenesSimple() {
    }

	
    public TecEstadoimagenesSimple(byte idestadoimagen) {
        this.idestadoimagen = idestadoimagen;
    }
    public TecEstadoimagenesSimple(byte idestadoimagen, String estado) {
       this.idestadoimagen = idestadoimagen;
       this.estado = estado;
    }
   
     @Id 

    
    @Column(name="IDESTADOIMAGEN", unique=true, nullable=false, precision=2, scale=0)
    public byte getIdestadoimagen() {
        return this.idestadoimagen;
    }
    
    public void setIdestadoimagen(byte idestadoimagen) {
        this.idestadoimagen = idestadoimagen;
    }

    
    @Column(name="ESTADO", length=50)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }





}


