package reversedb.simple;
// Generated Jun 10, 2015 7:53:33 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TecEstatustramite generated by hbm2java
 */
@Entity
@Table(name="TEC_ESTATUSTRAMITE"
)
public class TecEstatustramiteSimple  implements java.io.Serializable {


     private byte idestatustramite;
     private String descripcionEstadotramite;
     private Date fechaAlta;
     private Date fechaBaja;

    public TecEstatustramiteSimple() {
    }

	
    public TecEstatustramiteSimple(byte idestatustramite, String descripcionEstadotramite) {
        this.idestatustramite = idestatustramite;
        this.descripcionEstadotramite = descripcionEstadotramite;
    }
    public TecEstatustramiteSimple(byte idestatustramite, String descripcionEstadotramite, Date fechaAlta, Date fechaBaja) {
       this.idestatustramite = idestatustramite;
       this.descripcionEstadotramite = descripcionEstadotramite;
       this.fechaAlta = fechaAlta;
       this.fechaBaja = fechaBaja;
    }
   
     @Id 
    @Column(name="IDESTATUSTRAMITE", unique=true, nullable=false, precision=2, scale=0)
    public byte getIdestatustramite() {
        return this.idestatustramite;
    }
    
    public void setIdestatustramite(byte idestatustramite) {
        this.idestatustramite = idestatustramite;
    }

    
    @Column(name="DESCRIPCION_ESTADOTRAMITE", nullable=false, length=50)
    public String getDescripcionEstadotramite() {
        return this.descripcionEstadotramite;
    }
    
    public void setDescripcionEstadotramite(String descripcionEstadotramite) {
        this.descripcionEstadotramite = descripcionEstadotramite;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_ALTA", length=7)
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_BAJA", length=7)
    public Date getFechaBaja() {
        return this.fechaBaja;
    }
    
    public void setFechaBaja(Date fechaBaja) {
        this.fechaBaja = fechaBaja;
    }





}


